models/post.py
#!/usr/bin/python3
'''
Post Model
'''

from models.base_model import Base, BaseModel
from uuid import uuid4
from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, func
from sqlalchemy import create_engine, ForeignKey, Sequence
from sqlalchemy.orm import relationship
from datetime import datetime


class Post(BaseModel, Base):
    '''Representation of post'''
    __tablename__ = 'posts'

    id = Column(Integer, Sequence('post_id_seq', start=1, increment=1),
                     primary_key=True)
    description = Column(String(256), nullable=False)
    location = Column(String(256), nullable=False)
    comment = Column(String(256), nullable=False)
    price = Column(Integer, nullable=False)
    image = Column(String(120), default='image.jpg')
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime, default=func.now())
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now())

    def __init__(self, description, price, location, comment, image, user_id):
        ''' Initializes instance of the class '''
        self.description = description
        self.comment = comment
        self.price = price
        self.location = location
        self.image = image
        self.user_id = user_id
        self.created_at = datetime.utcnow()
        self.updated_at = datetime.utcnow()

views/view.py
#!/usr/bin/python3
""" User view Blueprint"""
from flask import Flask, Blueprint, render_template, flash, request, current_app, abort, redirect, url_for
from flask_login import LoginManager, login_required, current_user
from flask_wtf import FlaskForm
from flask_bcrypt import Bcrypt
from models import storage
from models.user import User
from models.post import Post
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
import os
import secrets


view = Blueprint('view', __name__, template_folder='templates', static_folder='static')

def save_image(photo):
    """Saves a photo"""
    if photo:
        hash_photo = secrets.token_urlsafe(10)
        _, file_extension = os.path.splitext(photo.filename)
        photo_name = hash_photo + file_extension
        file_path = os.path.join(current_app.root_path, 'static/img', photo_name)
        photo.save(file_path)
        return photo_name
    return None

@view.route('/post', methods=['GET', 'POST'])
@login_required
def add_post():
    """Enables a user to add a post"""
    if request.method == 'POST':
        description = request.form.get('description')
        price = request.form.get('price')
        location = request.form.get('location')
        comment = request.form.get('comment')
        photo = save_image(request.files.get('photo'))
        user_id = int (current_user.get_id())

        post = Post(description=description, price=price, location=location, comment=comment, image=photo, user_id=user_id)

        storage.new(post)
        storage.save()
        flash('Upload successful', 'info')
        return history()

    return render_template('post.html')

@view.route('/history')
def history():
    """Displays the user's post history"""
    from_delete = request.args.get('from_delete', default=0, type=int)
    from_update = request.args.get('from_update', default=0, type=int)

    if from_delete:
        flash('Select a post to delete')
    if from_update:
        flash('Select a post to update')
    user_id = current_user.id
    posts = storage.all(Post)
    
    user_posts = {}
    for k, v in posts.items():
        if v.user_id == user_id:
            user_posts[k] = v
    
    return render_template("gallery.html", from_delete=from_delete, from_update=from_update, posts=user_posts)


@view.route('/update/<post_id>', methods=['GET', 'POST'])
@login_required
def update(post_id):
    """Enables a user to update a post"""
    post = storage.get(Post, post_id)
    default_image = post.image

    if request.method == 'POST':
        post.description = request.form.get('description')
        post.price = request.form.get('price')
        post.location = request.form.get('location')
        post.comment = request.form.get('comment')

        new_image = save_image(request.files.get('photo'))
        if new_image:
            post.image = new_image
        else:
            post.image = default_image

        storage.save()

        flash('Update successful', 'info')
        return history()
    
    return render_template('update.html', post=post)



@view.route('/delete/<post_id>')
@login_required
def delete(post_id):
    """Deletes a users post"""
    storage.delete(Post, post_id)
    storage.save()
    flash('Deleted')
    return history()
    

@view.route('/post/<post_id>', methods=['GET'])
def post(post_id):
    """Displays one post"""
    from_delete = request.args.get('from_delete', default=0, type=int)
    from_update = request.args.get('from_update', default=0, type=int)

    post = storage.get(Post, post_id)
    if post:
        print(post.image)
    else:
        abort(404)

    return render_template('images.html', from_delete=from_delete, from_update=from_update, file=post)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
    <style>
      body {
          
            background-color: #f7bf50;
      }
  </style>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" >
      <a class="navbar-brand">
        <img src="{{ url_for('static', filename='Kibanda Eats-logos2.jpeg') }}" width="130" height="40" alt="Logo">
      </a>
        <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
         
          <a class="nav-item nav-link" id="home" href="/">Home</a>  
          {% if current_user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" 
                      data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                User {{ current_user.username | capitalize }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/history">History</a>
                <a class="dropdown-item" href="/post">Add Post</a>
                <a class="dropdown-item" href="{{ url_for('view.history', from_delete=1) }}">Delete Post</a>
                <a class="dropdown-item" href="{{ url_for('view.history', from_update=1) }}">Update Post</a>
                
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/logout">Log Out</a>
            </div>
          </li>
          {% else %}
            <a class="nav-item nav-link" id="login" href="/login">Login</a>
            <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
          
        </div>
      </div>
      
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %} {% if category ==
      'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
        {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}
    
    <div class="container">{% block content %} {% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>

templates/gallery.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}

<div>
    <form method="POST" action="{{ url_for('search_location')}}" class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search by location" aria-label="Search" name="location">
        <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
    <form method="POST" action="{{ url_for('search_price')}}" class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search by price" aria-label="Search" name="price">
        <button class="btn btn-outline-primary" type="submit">Search</button>
    </form>
    <br>
    <br>
</div>
<div class="container">

    <div class="row">

        <div class="col-lg-12">
        </div>
        {% if posts %}
            {% for key, value in posts.items() %}
    
                <div class="col-lg-3 col-md-4 col-sm-6">
                    <div class="card">
                        <a href="{{ url_for('view.post', from_delete=from_delete, from_update=from_update, post_id=value.id)}}">
                            <img class="card-img-top img-fluid" src=" {{url_for('static', filename=('img/' + value.image))}}" alt="{{ value.description }}">
                        </a>
                        <div class="card-body">
                            <p class="card-text">{{value.description}} for {{value.price}}.
                                <br>Found in {{value.location}}
                            </p>
                        </div>
                    </div>
                </div>           
                                
            {% endfor %}
        {% else %}
        <h3>No post available 
            Click here to add </h3>
        <br>
        <a class="btn btn-outline-primary" id="post" href="/post">Add a Post</a>
        {% endif%}
    </div>
</div>

{% endblock %}

templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<h1>Home Page</h1>
{% endblock %}

templates/images.html
{% extends "base.html" %}
{% block title %}Image{% endblock %}
{% block content %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <img img src=" {{url_for('static', filename=('img/' + file.image))}}" class="img-fluid" />
        </div>
        <div class="col-md-6">
            <div class="bg-light  p-4 border border-dark">
                <p>
                    Description: {{ file.description}}
                </p>
                <p>
                    Price: {{ file.price}}
                </p>
                <p>
                    Comment: {{ file.comment}}
                </p>
                <p>
                    Location: {{ file.location }}
                </p>
                <p>
                    Uploaded by: {{ file.user.username | capitalize }}
                </p>
                {% if current_user.id == file.user_id %}
                <div class="mt-3">
                    {% if from_delete %}
                    <a href="{{ url_for('view.delete', post_id=file.id)}}" class="btn btn-danger">Delete Post</a>
                    {% endif %}
                    {% if from_update %}
                    <a href="{{ url_for('view.update', post_id=file.id)}}" class="btn btn-primary">Update Post</a>
                    {% endif %}

                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password"
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
  {% endblock %}

templates/post.html
{% extends "base.html" %} {% block title %}Add Post{% endblock %}
{% block content %}
  <form method="POST" enctype="multipart/form-data">
    <h3 align="center">Add photo</h3>
    <div class="form-group">
      <label for="description">Description</label>
      <input
        type="description"
        class="form-control"
        id="description"
        name="description"
        placeholder="What was your meal"
        required
      />
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <input
          type="price"
          class="form-control"
          id="price"
          name="price"
          placeholder="How much was it?"
          required
        />
      </div>
      <div class="form-group">
        <label for="location">Location</label>
        <input
          type="location"
          class="form-control"
          id="location"
          name="location"
          placeholder="Give a detailed location where to find the food eg..Nairobi, Moi Avenue next to Jevajee Gardens"
          required
        />
      </div>
      <div class="form-group">
        <label for="comment">Comment</label>
        <input
          type="comment"
          class="form-control"
          id="comment"
          name="comment"
          placeholder="Give a comment"
          required
        />
      </div>
  
    <div class="form-group">
      <label for="photo">Photo</label>
      <input
        type="file"
        class="form-control"
        id="photo"
        name="photo"
        accept="image/*"
        placeholder="Upload photo"
        required
      />
    </div>
    <br />
    <button type="submit" value="Upload" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="userName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="userName"
        name="userName"
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1"
        placeholder="Enter password"
      />
    </div>
    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2"
        placeholder="Confirm password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
{% endblock %}

templates/update.html
{% extends "base.html" %}
{% block title %}Update{% endblock %}
{% block content %}


  <h3 align="center">Update Post</h3>
  <div class="col-md-6">
    <img img src=" {{url_for('static', filename=('img/' + post.image))}}" class="img-fluid" />
  </div>
  <form method="POST"  enctype="multipart/form-data">
    <div class="form-group">
      <label for="description">Description</label>
      <textarea
        type="description"
        class="form-control"
        id="description"
        name="description"
      >{{ post.description }}</textarea>
    </div>
    <div class="form-group">
        <label for="price">Price</label>
        <textarea
          type="price"
          class="form-control"
          id="price"
          name="price"
        >{{ post.price }}</textarea>
    </div>
    <div class="form-group">
        <label for="location">Location</label>
        <textarea
          type="location"
          class="form-control"
          id="location"
          name="location"
        >{{ post.location}}</textarea>
    </div>
    <div class="form-group">
        <label for="comment">Comment</label>
        <textarea
          type="comment"
          class="form-control"
          id="comment"
          name="comment"
        >{{ post.comment}}</textarea>
    </div>
  
    <div class="form-group">
        <label for="photo">Photo</label>
        <input
          type="file"
          class="form-control"
          id="photo"
          name="photo"
          accept="image/*"
          placeholder="Upload a different photo"
        />
    </div>
    <br>
    <button type="submit" value="Upload" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}